before_install:
# - sudo apt-get install hunspell hunspell-fr
# - sudo apt-get install enchant
 - sudo apt-get install texlive-font-utils
 - sudo apt-get install texlive-latex-extra
# - sudo apt-get install netpbm
# - sudo apt-get install poppler-utils
install:
 - pip3 install -U sphinx
# - pip3 install sphinxcontrib.spelling
language: python
python:
  - "3.6"
# command to run tests
script: bash travis.sh
